; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26729.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG213263 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG213264 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG213265 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG213627 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG213628 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG213629 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG213953 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG213954 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG213955 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG214279 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG214280 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG214281 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG214605 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG214606 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG214607 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG214931 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG214932 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG214933 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG215257 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG215258 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG215259 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG215583 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG215584 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG215585 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG208400 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208401 DB	'asize >= 0 && asize <= aalloc', 00H
	ORG $+2
$SG208409 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208410 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG208411 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208412 DB	'!x->ref.isStatic()', 00H
	ORG $+5
$SG208419 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208420 DB	'int(d->alloc) == aalloc', 00H
$SG208421 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208422 DB	'isDetached()', 00H
	ORG $+3
$SG208423 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+1
$SG208424 DB	'x == d', 00H
	ORG $+5
$SG208432 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208433 DB	'd->data()', 00H
	ORG $+6
$SG208434 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208435 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+6
$SG208436 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208437 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG208438 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208439 DB	'aalloc ? d != Data::sharedNull() : d == Data::sharedNull'
	DB	'()', 00H
	ORG $+5
$SG208440 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208441 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+7
$SG208442 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qvector'
	DB	'.h', 00H
	ORG $+5
$SG208443 DB	'd->size == asize', 00H
	ORG $+7
$SG216932 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG216933 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG216934 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG217258 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG217259 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG217260 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG209269 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG209270 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG209271 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG217615 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG217616 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG217617 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG209595 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG209596 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG209597 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG217941 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG217942 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG217943 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG209921 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG209922 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG209923 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG218267 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG218268 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG218269 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_OpsViewer@@3Uqt_meta_stringdata_OpsViewer_t@@B DD 0ffffffffH ; qt_meta_stringdata_OpsViewer
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	000000000000006aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000005eH
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000047H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000037H
	DB	04fH
	DB	070H
	DB	073H
	DB	056H
	DB	069H
	DB	065H
	DB	077H
	DB	065H
	DB	072H
	DB	00H
	DB	052H
	DB	065H
	DB	063H
	DB	076H
	DB	04dH
	DB	065H
	DB	073H
	DB	073H
	DB	061H
	DB	067H
	DB	065H
	DB	00H
	DB	00H
	DB	06dH
	DB	065H
	DB	073H
	DB	073H
	DB	061H
	DB	067H
	DB	065H
	DB	00H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	050H
	DB	069H
	DB	063H
	DB	00H
	ORG $+7
$SG218593 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+11
$SG218594 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG218595 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_data_OpsViewer@@3QBIB DD 07H			; qt_meta_data_OpsViewer
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	018H
	DD	02H
	DD	09H
	DD	04H
	DD	00H
	DD	01bH
	DD	02H
	DD	09H
	DD	02bH
	DD	0aH
	DD	03H
	DD	02bH
	DD	00H
	ORG $+4
$SG218919 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+11
$SG218920 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG218921 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG210739 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG210740 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG210741 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG219245 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG219246 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG219247 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG211113 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG211114 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG211115 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG219619 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG219620 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG219621 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG211439 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG211440 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG211441 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG219994 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG219995 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG219996 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG211814 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG211815 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG211816 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG212140 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG212141 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212142 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG220369 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG220370 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG220371 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG212466 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG212467 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212468 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG220745 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG220746 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG220747 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG204537 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG204538 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG204539 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG221071 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG221072 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG221073 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG212937 DB	'd:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG212938 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG212939 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@OpsViewer@@UEBAPEBUQMetaObject@@XZ	; OpsViewer::metaObject
PUBLIC	?qt_metacast@OpsViewer@@UEAAPEAXPEBD@Z		; OpsViewer::qt_metacast
PUBLIC	?qt_metacall@OpsViewer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; OpsViewer::qt_metacall
PUBLIC	?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; OpsViewer::qt_static_metacall
PUBLIC	?staticMetaObject@OpsViewer@@2UQMetaObject@@B	; OpsViewer::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?RecvMessage@OpsViewer@@IEAAXVQString@@@Z:PROC	; OpsViewer::RecvMessage
EXTRN	?ChangePic@OpsViewer@@IEAAXXZ:PROC		; OpsViewer::ChangePic
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@OpsViewer@@2UQMetaObject@@B DB 030H DUP (?) ; OpsViewer::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@OpsViewer@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@OpsViewer@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@OpsViewer@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@OpsViewer@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@OpsViewer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@OpsViewer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+140
	DD	imagerel $unwind$?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@OpsViewer@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@OpsViewer@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@OpsViewer@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@OpsViewer@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@OpsViewer@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@OpsViewer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0a217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@OpsViewer@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@OpsViewer@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'OpsViewer::staticMetaObject'', COMDAT
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 83
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@OpsViewer@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_OpsViewer@@3Uqt_meta_stringdata_OpsViewer_t@@B
	mov	QWORD PTR ?staticMetaObject@OpsViewer@@2UQMetaObject@@B+8, rax
; Line 84
	lea	rax, OFFSET FLAT:?qt_meta_data_OpsViewer@@3QBIB
	mov	QWORD PTR ?staticMetaObject@OpsViewer@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; OpsViewer::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@OpsViewer@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@OpsViewer@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@OpsViewer@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@OpsViewer@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'OpsViewer::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
$T2 = 48
tv86 = 56
$T3 = 64
_o$ = 96
_c$ = 104
_id$ = 112
_a$ = 120
?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; OpsViewer::qt_static_metacall
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 70
$LN10:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 71
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 72
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 74
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN4@qt_static_
$LN5@qt_static_:
; Line 75
	lea	rax, QWORD PTR $T3[rsp]
	mov	QWORD PTR $T2[rsp], rax
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T2[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv86[rsp], rax
	mov	rdx, QWORD PTR tv86[rsp]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?RecvMessage@OpsViewer@@IEAAXVQString@@@Z ; OpsViewer::RecvMessage
	jmp	SHORT $LN4@qt_static_
$LN6@qt_static_:
; Line 76
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?ChangePic@OpsViewer@@IEAAXXZ		; OpsViewer::ChangePic
$LN4@qt_static_:
; Line 80
	add	rsp, 88					; 00000058H
	ret	0
?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; OpsViewer::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@OpsViewer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; OpsViewer::qt_metacall
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 102
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 103
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 104
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 105
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 106
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 107
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 108
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@OpsViewer@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; OpsViewer::qt_static_metacall
$LN5@qt_metacal:
; Line 109
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 110
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 111
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 112
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 115
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 116
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@OpsViewer@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; OpsViewer::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@OpsViewer@@UEAAPEAXPEBD@Z PROC		; OpsViewer::qt_metacast
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 94
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 95
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 96
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_OpsViewer@@3Uqt_meta_stringdata_OpsViewer_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 97
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 98
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 99
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@OpsViewer@@UEAAPEAXPEBD@Z ENDP		; OpsViewer::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@OpsViewer@@UEBAPEBUQMetaObject@@XZ PROC	; OpsViewer::metaObject
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 89
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 90
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@OpsViewer@@2UQMetaObject@@B ; OpsViewer::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 91
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@OpsViewer@@UEBAPEBUQMetaObject@@XZ ENDP	; OpsViewer::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\soft\qt5.10\5.10.1\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 119
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\qtproject\opsviewer\debug\moc_opsviewer.cpp
; Line 119
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
